name: Deploy Docs

on:
  push:
    branches:
      - main  # Проверьте, как называется ваша ветка (main или master)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: python -m mkdocs gh-deploy --force
